# Auto-generated from docs/schema.md. Do not edit by hand.
from pyspark.sql import types as T

SCHEMA_COLUMNS = [
    "flight_date",
    "airline_code",
    "airline_name",
    "flight_number",
    "tail_number",
    "origin",
    "origin_city",
    "dest",
    "dest_city",
    "scheduled_dep",
    "dep_time",
    "dep_delay_minutes",
    "scheduled_arr",
    "arr_time",
    "arr_delay_minutes",
    "cancelled",
    "cancellation_code",
    "diverted",
    "wheels_off",
    "wheels_on",
    "taxi_out_minutes",
    "taxi_in_minutes",
    "air_time_minutes",
    "distance_miles",
    "equipment",
    "data_source",
    "ingest_ts",
]

SCHEMA = T.StructType(
    [
        T.StructField("flight_date", T.DateType(), True),
        T.StructField("airline_code", T.StringType(), True),
        T.StructField("airline_name", T.StringType(), True),
        T.StructField("flight_number", T.StringType(), True),
        T.StructField("tail_number", T.StringType(), True),
        T.StructField("origin", T.StringType(), True),
        T.StructField("origin_city", T.StringType(), True),
        T.StructField("dest", T.StringType(), True),
        T.StructField("dest_city", T.StringType(), True),
        T.StructField("scheduled_dep", T.TimestampType(), True),
        T.StructField("dep_time", T.TimestampType(), True),
        T.StructField("dep_delay_minutes", T.IntegerType(), True),
        T.StructField("scheduled_arr", T.TimestampType(), True),
        T.StructField("arr_time", T.TimestampType(), True),
        T.StructField("arr_delay_minutes", T.IntegerType(), True),
        T.StructField("cancelled", T.BooleanType(), True),
        T.StructField("cancellation_code", T.StringType(), True),
        T.StructField("diverted", T.BooleanType(), True),
        T.StructField("wheels_off", T.TimestampType(), True),
        T.StructField("wheels_on", T.TimestampType(), True),
        T.StructField("taxi_out_minutes", T.IntegerType(), True),
        T.StructField("taxi_in_minutes", T.IntegerType(), True),
        T.StructField("air_time_minutes", T.IntegerType(), True),
        T.StructField("distance_miles", T.IntegerType(), True),
        T.StructField("equipment", T.StringType(), True),
        T.StructField("data_source", T.StringType(), True),
        T.StructField("ingest_ts", T.TimestampType(), True),
    ]
)
